import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar, { type Menu } from "@/components/app/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const home: Menu = { name: "Components", url: "/" };
  const menus: Menu[] = [
    { name: "About Component", url: "/about" },
    { name: "Component Properties", url: "/props" },
    { name: "Component States", url: "/states" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar home={home} menus={menus} />

        <main className="px-8 py-4">{children}</main>
      </body>
    </html>
  );
}
